function [fitresult, gof] = createFit(frequencies, S11data)
%CREATEFIT(FREQUENCIES,S11DATA)
%  Create a fit.
%  
%  Data for 'untitled fit 1' fit:
%      X Input: frequencies
%      Y Output: S11data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
 
%  Auto-generated by MATLAB on 20-Mar-2023 13:43:50
 

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( frequencies, S11data );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 1.4197e-18;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'S11data vs. frequencies', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'frequencies', 'Interpreter', 'none' );
ylabel( 'S11data', 'Interpreter', 'none' );
grid on


